import { useState } from "react";
import { toast } from "sonner";
import {
  FileSignature, FileText, CheckCircle2, Clock, AlertTriangle, Send,
  Download, Plus, Users, DollarSign, Calendar, Shield, Pen, Eye, X,
  Mail, MessageSquare, Printer, Copy, ChevronDown, ChevronUp
} from "lucide-react";

interface Contract {
  id: string;
  client: string;
  clientDoc: string;
  clientEmail: string;
  company: string;
  type: string;
  value: string;
  paymentMethod: string;
  status: "draft" | "sent" | "signed" | "expired" | "cancelled";
  createdAt: string;
  signedAt?: string;
  expiresAt: string;
  signPlatform: string;
  services: string[];
  autoGenerated: boolean;
}

const contracts: Contract[] = [
  { id: "CTR-001", client: "João Silva", clientDoc: "12.345.678/0001-90", clientEmail: "joao@studio.com", company: "Studio Digital", type: "Gestão de Tráfego + Automação + Copy", value: "R$ 8.500/mês", paymentMethod: "PIX", status: "signed", createdAt: "2025-06-01", signedAt: "2025-06-02", expiresAt: "2026-06-01", signPlatform: "Clicksign", services: ["Google Ads", "Meta Ads", "n8n Automação", "Copywriting"], autoGenerated: true },
  { id: "CTR-002", client: "Maria Santos", clientDoc: "98.765.432/0001-10", clientEmail: "maria@ecommerce.com", company: "E-commerce Plus", type: "Automação + Email Marketing", value: "R$ 12.000/mês", paymentMethod: "Cartão de Crédito", status: "signed", createdAt: "2025-08-01", signedAt: "2025-08-03", expiresAt: "2026-08-01", signPlatform: "DocuSign", services: ["n8n", "ManyChat", "ActiveCampaign"], autoGenerated: true },
  { id: "CTR-003", client: "Carlos Lima", clientDoc: "456.789.123-00", clientEmail: "carlos@sabor.com", company: "Restaurante Sabor", type: "Google Negócio + Social Media", value: "R$ 2.000/mês", paymentMethod: "PIX", status: "signed", createdAt: "2026-01-15", signedAt: "2026-01-16", expiresAt: "2027-01-15", signPlatform: "Autentique", services: ["Google Business", "Instagram"], autoGenerated: true },
  { id: "CTR-004", client: "InfoProduto BR", clientDoc: "11.222.333/0001-44", clientEmail: "contato@infoproduto.com", company: "InfoProduto BR", type: "Funil + Tráfego + Copy", value: "R$ 5.000/mês", paymentMethod: "Cartão de Débito", status: "cancelled", createdAt: "2025-09-01", signedAt: "2025-09-02", expiresAt: "2026-09-01", signPlatform: "ZapSign", services: ["Landing Page", "Meta Ads", "Copywriting"], autoGenerated: true },
];

const statusConfig = {
  draft: { label: "Rascunho", color: "text-muted-foreground bg-secondary", icon: Pen },
  sent: { label: "Enviado", color: "text-accent bg-accent/10", icon: Send },
  signed: { label: "Assinado", color: "text-green-400 bg-green-500/10", icon: CheckCircle2 },
  expired: { label: "Expirado", color: "text-amber-400 bg-amber-500/10", icon: Clock },
  cancelled: { label: "Cancelado", color: "text-destructive bg-destructive/10", icon: AlertTriangle },
};

export default function ContractsManager() {
  const [filter, setFilter] = useState<string>("all");
  const [showCreate, setShowCreate] = useState(false);
  const [viewingContract, setViewingContract] = useState<Contract | null>(null);

  const filtered = filter === "all" ? contracts : contracts.filter(c => c.status === filter);

  const stats = {
    total: contracts.length,
    signed: contracts.filter(c => c.status === "signed").length,
    pending: contracts.filter(c => c.status === "sent" || c.status === "draft").length,
    revenue: `R$ ${contracts.filter(c => c.status === "signed").reduce((a, c) => a + parseInt(c.value.replace(/\D/g, "")), 0).toLocaleString()}`,
  };

  const contractTemplate = (c: Contract) => `
CONTRATO DE PRESTAÇÃO DE SERVIÇOS DE MARKETING DIGITAL

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

CONTRATANTE:
Nome / Empresa: ${c.client} — ${c.company}
CPF/CNPJ: ${c.clientDoc}
Email: ${c.clientEmail}

CONTRATADA:
Orquestrador Digital — Centro de Operações de Marketing com IA

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

1. OBJETO DO CONTRATO
Prestação de serviços de marketing digital incluindo:
${c.services.map(s => `   • ${s}`).join("\n")}

2. PRAZO
O contrato tem duração de 12 (doze) meses, renováveis automaticamente.
Início: ${c.createdAt} | Vencimento: ${c.expiresAt}

3. VALORES
Valor mensal do serviço: ${c.value}
Pagamento via: ${c.paymentMethod}

4. INVESTIMENTO EM ANÚNCIOS
O valor investido em anúncios NÃO está incluído no valor do serviço.
Esse valor é pago diretamente pelo cliente às plataformas de anúncios.

5. RESPONSABILIDADE SOBRE RESULTADOS
A contratada se compromete a aplicar estratégias profissionais de marketing,
porém não garante resultados financeiros específicos, pois dependem de fatores
externos como: mercado, concorrência, produto e atendimento do cliente.

6. OBRIGAÇÕES DO CLIENTE
O cliente deve:
   • Fornecer acesso às plataformas
   • Fornecer materiais necessários
   • Responder solicitações da equipe em até 48h
Caso o cliente não forneça informações necessárias, o prazo pode ser alterado.

7. ATRASO DE PAGAMENTO
Em caso de atraso:
   • 3 dias → Aviso por email e WhatsApp
   • 7 dias → Suspensão do serviço
   • 15 dias → Cancelamento automático do contrato

8. CANCELAMENTO
Cancelamento deve ser solicitado com 30 dias de antecedência por escrito.

9. LIMITAÇÃO DE RESPONSABILIDADE
A contratada não se responsabiliza por:
   • Bloqueios de contas de anúncios pelas plataformas
   • Mudanças de algoritmos das plataformas
   • Problemas técnicos de terceiros

10. CONFIDENCIALIDADE
Todas as informações do cliente serão tratadas com total confidencialidade.
Dados sensíveis são criptografados e armazenados com segurança.

11. ACEITE
O contrato é considerado válido após assinatura digital via ${c.signPlatform}.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Assinatura Digital: ${c.signedAt ? `Assinado em ${c.signedAt}` : "Aguardando assinatura"}
Plataforma: ${c.signPlatform}
IP do aceite: Registrado automaticamente
  `.trim();

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold text-foreground flex items-center gap-3">
            <FileSignature className="w-7 h-7 text-primary" /> Contract Engine
          </h1>
          <p className="text-sm text-muted-foreground mt-1">Geração automática de contratos profissionais, assinatura digital e proteção legal completa.</p>
        </div>
        <button onClick={() => setShowCreate(!showCreate)} className="flex items-center gap-2 px-4 py-2 bg-primary text-primary-foreground rounded-lg text-sm font-medium hover:opacity-90">
          <Plus className="w-4 h-4" /> Gerar Contrato
        </button>
      </div>

      {/* Stats */}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
        {[
          { icon: FileText, label: "Total", value: stats.total, color: "text-foreground", iconColor: "text-primary" },
          { icon: CheckCircle2, label: "Assinados", value: stats.signed, color: "text-green-400", iconColor: "text-green-400" },
          { icon: Clock, label: "Pendentes", value: stats.pending, color: "text-accent", iconColor: "text-accent" },
          { icon: DollarSign, label: "Receita Mensal", value: stats.revenue, color: "text-primary", iconColor: "text-primary" },
        ].map((s, i) => (
          <div key={i} className="rounded-xl border border-border bg-card p-4 text-center">
            <s.icon className={`w-5 h-5 mx-auto mb-2 ${s.iconColor}`} />
            <p className={`text-2xl font-bold ${s.color}`}>{s.value}</p>
            <p className="text-[10px] text-muted-foreground">{s.label}</p>
          </div>
        ))}
      </div>

      {/* Automatic Flow */}
      <div className="rounded-xl border border-primary/20 bg-primary/5 p-5">
        <h3 className="text-sm font-semibold text-foreground mb-3 flex items-center gap-2"><Shield className="w-4 h-4 text-primary" /> Fluxo Automático do Contrato</h3>
        <div className="flex flex-wrap gap-2 items-center text-[10px]">
          {["Cliente Cadastrado", "→", "Serviço Selecionado", "→", "Contrato Gerado pela IA", "→", "Enviado por Email", "→", "Assinatura Digital", "→", "Serviço Ativado"].map((step, i) => (
            <span key={i} className={step === "→" ? "text-primary font-bold text-sm" : "px-2.5 py-1.5 rounded-lg bg-card border border-border text-foreground font-medium"}>{step}</span>
          ))}
        </div>
        <p className="text-[10px] text-destructive mt-3 flex items-center gap-1"><AlertTriangle className="w-3 h-3" /> Sem contrato assinado = serviço NÃO inicia.</p>
      </div>

      {/* Signature Platforms */}
      <div className="rounded-xl border border-border bg-card p-4">
        <h3 className="text-sm font-semibold text-foreground mb-3 flex items-center gap-2"><Shield className="w-4 h-4 text-primary" /> Plataformas de Assinatura Digital</h3>
        <div className="flex flex-wrap gap-3">
          {["Clicksign", "Autentique", "DocuSign", "ZapSign"].map(p => (
            <span key={p} className="px-4 py-2 rounded-lg bg-secondary/50 border border-border text-xs text-foreground font-medium">{p}</span>
          ))}
        </div>
      </div>

      {/* Protection Rules */}
      <div className="rounded-xl border border-amber-500/20 bg-amber-500/5 p-5">
        <h3 className="text-sm font-semibold text-foreground mb-3 flex items-center gap-2"><Shield className="w-4 h-4 text-amber-400" /> Proteções Contra Clientes Problemáticos</h3>
        <div className="grid grid-cols-2 md:grid-cols-4 gap-2">
          {[
            "Serviço não inicia sem pagamento",
            "Renovação automática mensal",
            "Bloqueio automático em atraso",
            "Contrato obrigatório para todos",
          ].map((rule, i) => (
            <div key={i} className="p-2 rounded-lg bg-card border border-border text-center">
              <CheckCircle2 className="w-4 h-4 mx-auto mb-1 text-green-400" />
              <p className="text-[10px] text-foreground">{rule}</p>
            </div>
          ))}
        </div>
      </div>

      {/* Create Form */}
      {showCreate && (
        <div className="rounded-xl border border-primary/30 bg-primary/5 p-5 space-y-4">
          <h3 className="text-sm font-semibold text-foreground">Gerar Novo Contrato com IA</h3>
          <p className="text-[10px] text-muted-foreground">O sistema preenche automaticamente: nome, empresa, serviço, valor, prazo, pagamento e data de início.</p>
          <div className="grid md:grid-cols-2 gap-4">
            <div><label className="text-[10px] text-muted-foreground font-semibold uppercase">Cliente</label>
              <select className="w-full mt-1 p-2 rounded-lg bg-card border border-border text-sm text-foreground">
                <option>Selecionar cliente...</option>
                <option>João Silva — Studio Digital</option>
                <option>Maria Santos — E-commerce Plus</option>
                <option>Carlos Lima — Restaurante Sabor</option>
              </select>
            </div>
            <div><label className="text-[10px] text-muted-foreground font-semibold uppercase">Valor Mensal</label>
              <input className="w-full mt-1 p-2 rounded-lg bg-card border border-border text-sm text-foreground" placeholder="R$ 0,00" />
            </div>
            <div><label className="text-[10px] text-muted-foreground font-semibold uppercase">Forma de Pagamento</label>
              <select className="w-full mt-1 p-2 rounded-lg bg-card border border-border text-sm text-foreground">
                <option>PIX</option><option>Cartão de Crédito</option><option>Cartão de Débito</option>
              </select>
            </div>
            <div><label className="text-[10px] text-muted-foreground font-semibold uppercase">Plataforma de Assinatura</label>
              <select className="w-full mt-1 p-2 rounded-lg bg-card border border-border text-sm text-foreground">
                <option>Clicksign</option><option>DocuSign</option><option>ZapSign</option><option>Autentique</option>
              </select>
            </div>
          </div>
          <button onClick={() => { toast.success("Contrato gerado pela IA e enviado para assinatura!"); setShowCreate(false); }} className="flex items-center gap-2 px-6 py-2 bg-primary text-primary-foreground rounded-lg text-sm font-bold hover:opacity-90">
            <Pen className="w-4 h-4" /> Gerar Contrato com IA
          </button>
        </div>
      )}

      {/* Filters */}
      <div className="flex gap-2 flex-wrap">
        {["all", "draft", "sent", "signed", "expired", "cancelled"].map(f => (
          <button key={f} onClick={() => setFilter(f)} className={`px-3 py-1.5 rounded-lg text-xs font-medium transition-all ${filter === f ? "bg-primary text-primary-foreground" : "bg-secondary/50 text-muted-foreground hover:text-foreground"}`}>
            {f === "all" ? "Todos" : statusConfig[f as keyof typeof statusConfig].label}
          </button>
        ))}
      </div>

      {/* Contracts Table */}
      <div className="rounded-xl border border-border bg-card overflow-hidden">
        <div className="overflow-x-auto">
          <table className="w-full text-sm">
            <thead><tr className="border-b border-border bg-secondary/30">
              <th className="p-3 text-left text-xs text-muted-foreground">ID</th>
              <th className="p-3 text-left text-xs text-muted-foreground">Cliente</th>
              <th className="p-3 text-left text-xs text-muted-foreground">Tipo</th>
              <th className="p-3 text-left text-xs text-muted-foreground">Valor</th>
              <th className="p-3 text-left text-xs text-muted-foreground">Pagamento</th>
              <th className="p-3 text-left text-xs text-muted-foreground">Status</th>
              <th className="p-3 text-left text-xs text-muted-foreground">Assinatura</th>
              <th className="p-3 text-left text-xs text-muted-foreground">Ações</th>
            </tr></thead>
            <tbody>
              {filtered.map(c => {
                const cfg = statusConfig[c.status];
                const Icon = cfg.icon;
                return (
                  <tr key={c.id} className="border-b border-border/50 hover:bg-secondary/20">
                    <td className="p-3 text-xs font-mono text-primary">{c.id}</td>
                    <td className="p-3"><p className="text-xs font-semibold text-foreground">{c.client}</p><p className="text-[10px] text-muted-foreground">{c.company}</p></td>
                    <td className="p-3 text-xs text-muted-foreground">{c.type}</td>
                    <td className="p-3 text-xs text-primary font-bold">{c.value}</td>
                    <td className="p-3 text-xs text-muted-foreground">{c.paymentMethod}</td>
                    <td className="p-3"><span className={`flex items-center gap-1 text-[10px] font-medium px-2 py-1 rounded-full w-fit ${cfg.color}`}><Icon className="w-3 h-3" /> {cfg.label}</span></td>
                    <td className="p-3 text-xs text-muted-foreground">{c.signPlatform}</td>
                    <td className="p-3 flex gap-1">
                      <button onClick={() => setViewingContract(c)} className="p-1.5 rounded-lg hover:bg-secondary/50 text-muted-foreground hover:text-foreground"><Eye className="w-3.5 h-3.5" /></button>
                      <button className="p-1.5 rounded-lg hover:bg-secondary/50 text-muted-foreground hover:text-foreground"><Download className="w-3.5 h-3.5" /></button>
                      {c.status === "draft" && <button className="p-1.5 rounded-lg hover:bg-accent/10 text-accent"><Send className="w-3.5 h-3.5" /></button>}
                    </td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        </div>
      </div>

      {/* Contract View Modal */}
      {viewingContract && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-background/80 backdrop-blur-sm p-4" onClick={() => setViewingContract(null)}>
          <div className="bg-card border border-border rounded-xl p-6 w-full max-w-3xl max-h-[90vh] overflow-y-auto space-y-4" onClick={e => e.stopPropagation()}>
            <div className="flex items-center justify-between">
              <h2 className="text-lg font-bold text-foreground flex items-center gap-2"><FileSignature className="w-5 h-5 text-primary" /> {viewingContract.id} — Contrato Completo</h2>
              <div className="flex items-center gap-2">
                <button onClick={() => { navigator.clipboard.writeText(contractTemplate(viewingContract)); toast.success("Contrato copiado!"); }} className="p-2 rounded-lg hover:bg-secondary text-muted-foreground"><Copy className="w-4 h-4" /></button>
                <button onClick={() => setViewingContract(null)} className="p-1 rounded hover:bg-secondary"><X className="w-4 h-4" /></button>
              </div>
            </div>
            <pre className="text-xs text-foreground/80 leading-relaxed whitespace-pre-wrap font-mono bg-secondary/20 p-4 rounded-lg border border-border">
              {contractTemplate(viewingContract)}
            </pre>
          </div>
        </div>
      )}
    </div>
  );
}
